name: pull-request-terraform-validate

on: [pull_request]

jobs:
  pull-request-terraform-validate:
    runs-on: ubuntu-latest
    name: Validate Terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate